# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  GATSBY_API_BASE_URL = "https://testresource-server.openstack.org"  
  GATSBY_SPONSORED_PROJECT_ID = "5"  